TFP-2727 Regner ut andeler forholdsmessig
navikt/fp-sak pull request #235
Opened 2020-03-20 14:56 UTC by EirikVimmeNav

2020-03-23 07:43 UTC, palfi requested changes

2020-03-24 08:27 UTC, pekern reviewed
Ikke noe ekstra å utsette på utenom det anders kommenterer

2020-03-26 14:44 UTC, palfi requested changes

2020-03-30 06:34 UTC, palfi requested changes

2020-03-31 13:41 UTC, palfi approved these changes

2020-03-31 13:48 UTC, merged