TFP-4438 Lagt inn funksjonalitet som avgjør om besteberegning gir sek…
navikt/fp-sak pull request #5728
Opened 2023-04-26 14:12 UTC by AnjaAalerud

…sAvDeTiBeste eller ordnære beregningsregler, og mapper til formidling. Dette for å kunne gi riktig tekst i brev i de ulike tilfellene ved besteberegning. Tar inn ny versjon av fp_kontrakter

2023-04-27 11:30 UTC, pekern requested changes

2023-04-27 11:30 UTC, pekern commented on web/src/main/java/no/nav/foreldrepenger/web/app/tjenester/formidling/beregningsgrunnlag/BeregningsgrunnlagFormidlingV2DtoTjeneste.java
> +        var ordinærtBeregnetBeløp = beregningsGrunnlagPerioder.get(0).getBeregnetPrÅr();
Husk at andel.overstyrtPrår vil være satt hvis den har gått til avviksvurdering, så du bør bruke denne istedenfor beregnetPrÅr om den er satt. Noe slik:

`beregningsgrunnlagperioder.get(0)
            .getBeregningsgrunnlagPrStatusOgAndelList()
            .stream().map(andel -> andel.getOverstyrtPrÅr() != null ? andel.getOverstyrtPrÅr() : andel.getBeregnetPrÅr()).reduce(BigDecimal::add)
            .orElse(BigDecimal.ZERO);`

2023-04-27 11:45 UTC, AnjaAalerud commented on web/src/main/java/no/nav/foreldrepenger/web/app/tjenester/formidling/beregningsgrunnlag/BeregningsgrunnlagFormidlingV2DtoTjeneste.java
> +        var ordinærtBeregnetBeløp = beregningsGrunnlagPerioder.get(0).getBeregnetPrÅr();
Takk, har oppdatert

2023-04-28 08:21 UTC, pekern approved these changes

2023-04-28 10:24 UTC, merged