cleanup, method references istf lambda + simplify stream chains
navikt/fp-sak pull request #5891
Opened 2023-07-10 12:36 UTC by palfi

2023-07-10 14:05 UTC, espenwaaga requested changes

2023-07-10 14:05 UTC, espenwaaga commented on domenetjenester/uttak/src/main/java/no/nav/foreldrepenger/domene/uttak/PersonopplysningerForUttakImpl.java
> +import no.nav.foreldrepenger.behandlingslager.behandling.personopplysning.*;
Se kommentar over. import samlet i *

2023-07-10 14:05 UTC, espenwaaga commented on domenetjenester/uttak/src/main/java/no/nav/foreldrepenger/domene/uttak/fastsetteperioder/grunnlagbyggere/SøknadGrunnlagBygger.java
> +import no.nav.foreldrepenger.regler.uttak.fastsetteperiode.grunnlag.*;
samme som over

2023-07-10 14:05 UTC, espenwaaga commented on web/src/main/java/no/nav/foreldrepenger/web/app/tjenester/behandling/uttak/app/SaldoerDtoTjeneste.java
> +import no.nav.foreldrepenger.regler.uttak.fastsetteperiode.grunnlag.*;
import *

2023-07-11 05:38 UTC, palfi commented on behandlingslager/domene/src/main/java/no/nav/foreldrepenger/behandlingslager/behandling/Behandling.java
> +        return behandlingStegTilstander.stream().min(comparator);
Intellij som gjorde hele committen for meg, så regner med at det er riktig

2023-07-11 05:41 UTC, palfi commented on domenetjenester/behandling-revurdering/src/test/java/no/nav/foreldrepenger/behandling/revurdering/satsregulering/GrunnbeløpReguleringTaskTest.java
> +import no.nav.foreldrepenger.behandlingslager.behandling.*;
intellij refaktor som ikke var så smart

2023-07-11 05:48 UTC, palfi commented on behandlingslager/domene/src/main/java/no/nav/foreldrepenger/behandlingslager/behandling/Behandling.java
> +        return behandlingStegTilstander.stream().min(comparator);
Hvis jeg endrer til max så er det minst en test som feiler, så min virker riktig

2023-07-11 06:40 UTC, espenwaaga commented on behandlingslager/domene/src/main/java/no/nav/foreldrepenger/behandlingslager/behandling/Behandling.java
> +        return behandlingStegTilstander.stream().min(comparator);
Sounds good 👍

2023-07-11 06:41 UTC, espenwaaga approved these changes

2023-07-11 06:49 UTC, merged